spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://satyabhushan8887:08&October&1998@cluster0.hxb5n.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

#logging:
#  level:
#    root: INFO
#sonar:
#  host:
#    url: http://localhost:9000</sonar
#  login: admin
#  password: 08&October&1998